[package]
name = "del-raycast-cudarc-kernel"
description = "hogehoge"

[dependencies]

[build-dependencies]
bindgen_cuda = "0.1.5"
# del-geo-cpp-headers = {path="../../del-geo/del-geo-cpp-headers"}
del-geo-cpp-headers = {git = "https://github.com/nobuyuki83/del-geo.git"}


